### ISSUE TITLE
Running in background

### ISSUE THREAD

**Issue by solancer** [m3ng9i/ran#10]
If I run RAN in the background how can I stop it or start it again?

**Comment by m3ng9i** [comment]
Stop: Use *ps* command to find the pid of ran, and then use *kill* command to stop it.

example:

`ps -C ran -o pid= | xargs -I {} kill {}`

You can also use any process manager provided by the OS to stop ran.

Start ran in background: 

`ran -l &`

**Comment by solancer** [comment]
perfect, also the below code also worked fine to stop the process

`kill -9 $(lsof -t -i:8080)`
