### ISSUE TITLE
404 with special characters in URL

### ISSUE THREAD

**Issue by ddwwcruz** [m3ng9i/ran#19]
OS: Linux (Ubuntu 18.04)

Some of my files have special characters like `'` or `"`. Files and directories with these special characters display the 404 page instead of the file.

**Comment by m3ng9i** [comment]
ran v0.1.4 is released, try the new version: <https://github.com/m3ng9i/ran/releases>

**Comment by ddwwcruz** [comment]
yes this fixes the issue.

thank you
