### ISSUE TITLE
Print URL to console

### ISSUE THREAD

**Issue by hickford** [m3ng9i/ran#6]
```
System: Ran is running on HTTP port 8080
```

It would be useful if the app printed a URL to console when the server starts, so you can copy-and-paste it to your web browser. Some terminals (gnome-terminal I know) even hyperlink URLs.

```
Listening on http://127.0.0.1:8080
Listening on http://10.254.216.72.:8080
```

**Comment by m3ng9i** [comment]
Good suggestion. I have updated the code to v0.1.3. You can go to the [release page](https://github.com/m3ng9i/ran/releases) to download the latast Ran binary.
